version: '3.7'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "80:8080"
    volumes:
      - ./Meowmed+_REST.yaml:/usr/share/nginx/html/Meowmed+_REST.yaml
    environment:
      API_URL: ./Meowmed+_REST.yaml

  ui.rda:
    build:
      args:
        mode: "prod"
        customerService: "http://customer.rda:8080"
        policyService: "http://policy.rda:8080"
      context: ./UI
      dockerfile: Dockerfile
    container_name: ui-service
    env_file:
      - ./UI/ui.env
    networks:
      - "default"
    ports:
      - 81:8000
    depends_on:
      - policy.rda
      - customer.rda
  policy.rda:
    build:
      context: ./RDA/PolicyService
      dockerfile: Dockerfile
    container_name: policy-service-rda
    networks:
      - "default"
    ports:
      - 8082:8080
    depends_on:
      - policydb.rda
    environment:
      - spring.datasource.url=jdbc:mariadb://policydb.rda:3306/Policy
      - spring.datasource.username=user
      - spring.datasource.password=123456789
      - docker_customerurl=customer
      - docker_notificationurl=notification.rda
      - docker_debugmode=false
  policydb.rda:
    image: mariadb:latest
    container_name: policydb-rda
    networks:
      - "default"
    environment:
      MARIADB_ROOT_PASSWORD: test
      MYSQL_DATABASE: Policy
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456789
    #ports:
    #  - "3306:3306"
    volumes:
      - policydb_data_rda:/var/lib/mysql
  customer.rda:
    build:
      context: ./RDA/CustomerService
      dockerfile: Dockerfile
    container_name: customer-service-rda
    depends_on:
      - customerdb.rda
    networks:
      - "default"
    ports:
      - 8081:8080
    environment:
      - spring.datasource.url=jdbc:mariadb://customerdb.rda:3306/Customer
      - spring.datasource.username=user
      - spring.datasource.password=123456789
      - docker_notificationurl=notification.rda
  customerdb.rda:
    image: mariadb:latest
    container_name: customerdb-rda
    networks:
      - "default"
    environment:
      MARIADB_ROOT_PASSWORD: test
      MYSQL_DATABASE: Customer
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456789
    #ports:
    #  - "3306:3306"
    volumes:
      - customerdb_data_rda:/var/lib/mysql
  notification.rda:
    build:
      context: ./RDA/NotificationService
      dockerfile: Dockerfile
    container_name: notification-service-rda
    networks:
      - "default"
    environment:
      - spring_mail_host=smtp.gmail.com
      - spring_mail_port=587
      - spring_mail_username=meowmedservice@gmail.com
      - spring_mail_password=yqanpbjhupnllbcz
      - spring_mail_properties.mail.smtp.auth=true
      - spring_mail_properties.mail.smtp.starttls.enable=true

  ui.eda:
    build:
      args:
        mode: "prod"
        customerService: "http://customer.eda:8081"
        policyService: "http://policy.eda:8080"
      context: ./UI
      dockerfile: Dockerfile
    container_name: ui-service-eda
    env_file:
      - ./UI/ui.env
    networks:
      - "default"
    ports:
      - "82:8000"
    depends_on:
      - customer.eda
      - policy.eda
  customer.eda:
    build:
      context: ./EDA/
      dockerfile: ./CustomerService/Dockerfile
      args:
        service: CustomerService
    container_name: customer-service-eda
    networks:
      - "default"
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.datasource.url=jdbc:mariadb://customerdb.eda:3306/Customer
      - spring.datasource.username=root
      - spring.datasource.password=test
      - spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
      #    - spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
    ports:
      - "8071:8081"
    depends_on:
      - customerdb.eda
      - rabbitmq
  customerdb.eda:
    image: mariadb:latest
    container_name: customerdb-eda
    command: --general-log=1
    networks:
      - "default"
    environment:
      MARIADB_ROOT_PASSWORD: test
      MYSQL_DATABASE: Customer
      MYSQL_USER: user
      MYSQL_PASSWORD: test12345
  notification.eda:
    build:
      context: ./EDA/
      dockerfile: ./NotificationService/Dockerfile
      args:
        service: NotificationService
    container_name: notification-service-eda
    networks:
      - "default"
    environment:
      - spring.rabbitmq.host=rabbitmq
    depends_on:
      - rabbitmq
  policy.eda:
    build:
      context: ./EDA/
      dockerfile: ./PolicyService/Dockerfile
      args:
        service: PolicyService
    container_name: policy-service-eda
    depends_on:
      - policydb.eda
      - rabbitmq
    networks:
      - "default"
    ports:
      - "8072:8080"
    environment:
      - RABBIT_HOST=rabbitmq
      - spring.datasource.url=jdbc:mariadb://policydb.eda:3306/Policy
      - spring.datasource.username=user
      - spring.datasource.password=123456789
  policydb.eda:
    image: mariadb:latest
    container_name: policydb-eda
    networks:
      - "default"
    environment:
      MARIADB_ROOT_PASSWORD: test
      MYSQL_DATABASE: Policy
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456789
    #ports:
    #  - "3306:3306"
    volumes:
      - policydb_data_eda:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    networks:
      - "default"
    ports:
      - "15671:15671"
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"

volumes:
  policydb_data_eda:
  customerdb_data_rda:
  policydb_data_rda:
