#! /bin/sh
docker compose --profile rda --profile eda build
mkdir -p target
docker images meowmed-* --format '{{.Repository}}' | tr '\n' ' ' | xargs docker save | gzip > target/meowmed.tar.gz
cp docker-compose.yaml target/
