version: '3.7'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "81:8080"
    volumes:
      - ./Meowmed+_REST.yaml:/usr/share/nginx/html/Meowmed+_REST.yaml
    environment:
      API_URL: ./Meowmed+_REST.yaml

  ui.rda:
    build: ./UI
  customer.rda:
    build: ./RDA/CustomerService
    ports:
      - "8081:8080"
  policy.rda:
    build: ./RDA/PolicyService
    ports:
      - "8082:8080"
  notification.rda:
    build: ./RDA/NotificationService
      
  ui.eda:
    build: ./UI
  customer.eda:
    build:
      context: ./EDA
      dockerfile: ./CustomerService/Dockerfile
      args:
        service: CustomerService
    ports:
      - "8071:8080"
  policy.eda:
    build:
      context: ./EDA
      dockerfile: ./PolicyService/Dockerfile
      args:
        service: PolicyService
    ports:
      - "8072:8080"
  notification.eda:
    build:
      context: ./EDA
      dockerfile: ./NotificationService/Dockerfile
      args:
        service: NotificationService
