#! /bin/sh
docker compose --profile rda --profile eda build

docker images meowmed-*.eda:latest --format '{{.Repository}}' | tr '\n' ' ' | xargs docker save | gzip > meowmed-eda.tar.gz
docker images meowmed-*.rda:latest --format '{{.Repository}}' | tr '\n' ' ' | xargs docker save | gzip > meowmed-rda.tar.gz