version: '3.7'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "81:8080"
    volumes:
      - ./Meowmed+_REST.yaml:/usr/share/nginx/html/Meowmed+_REST.yaml
    environment:
      API_URL: ./Meowmed+_REST.yaml
  ui:
    build:
      context: ./UI
      target: prod
    environment:
      - DENO_DEPLOYMENT_ID=2baff8832ead514a9cff77a18f43810bf19be235

  policy.rda:
    build:
      context: ./RDA/PolicyService
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
  customer.rda:
    build:
      context: ./RDA/CustomerService
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
  notification.rda:
    build:
      context: ./RDA/NotificationService
      dockerfile: Dockerfile

  customer.eda:
    build:
      context: ./EDA/
      dockerfile: ./CustomerService/Dockerfile
      args:
        service: CustomerService
    ports:
      - "8071:8081"
  notification.eda:
    build:
      context: ./EDA/
      dockerfile: ./NotificationService/Dockerfile
      args:
        service: NotificationService
  policy.eda:
    build:
      context: ./EDA/
      dockerfile: ./PolicyService/Dockerfile
      args:
        service: PolicyService
    ports:
      - "8072:8080"
