version: '3.7'
services:
  ui.rda:
    image: meowmed-ui
    profiles:
      - rda
    environment:
      - MEOWMED_CUSTOMER_SERVER=http://customer.rda:8080
      - MEOWMED_POLICY_SERVER=http://policy.rda:8080
    ports:
      - "80:8000"
    depends_on:
      - policy.rda
      - customer.rda
  policy.rda:
    image: meowmed-policy.rda
    profiles:
      - rda
    depends_on:
      - policydb.rda
    environment:
      - spring.datasource.url=jdbc:mariadb://policydb.rda:3306/Policy
      - spring.datasource.username=user
      - spring.datasource.password=123456789
      - docker_customerurl=customer.rda
      - docker_notificationurl=notification.rda
      - docker_debugmode=true
  policydb.rda:
    image: mariadb:latest
    profiles:
      - rda
    environment: &dbcredentials
      MARIADB_ROOT_PASSWORD: test
      MYSQL_DATABASE: Policy
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456789
    volumes:
      - policydb_data_rda:/var/lib/mysql
    healthcheck: &dbhealthcheck
      test: "mariadb --user=root --password=$$MARIADB_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 20s
      retries: 10
  customer.rda:
    image: meowmed-customer.rda
    profiles:
      - rda
    depends_on:
      - customerdb.rda
    environment:
      - spring.datasource.url=jdbc:mariadb://customerdb.rda:3306/Customer
      - spring.datasource.username=user
      - spring.datasource.password=123456789
      - docker.notificationurl=notification.rda
      - docker.policyurl=policy.rda
  customerdb.rda:
    image: mariadb:latest
    profiles:
      - rda
    environment:
      <<: *dbcredentials
      MYSQL_DATABASE: Customer
    volumes:
      - customerdb_data_rda:/var/lib/mysql
    healthcheck:
      <<: *dbhealthcheck
  notification.rda:
    image: meowmed-notification.rda
    profiles:
      - rda
    environment:
      - spring_mail_port=587
      - spring_mail_host=smtp.gmail.com
      - spring_mail_username=meowmedservice@gmail.com
      - spring_mail_password=yqanpbjhupnllbcz
      - spring_mail_properties.mail.smtp.auth=true
      - spring_mail_properties.mail.smtp.starttls.enable=true

  ui.eda:
    image: meowmed-ui
    profiles:
      - eda
    environment:
      - MEOWMED_CUSTOMER_SERVER=http://customer.eda:8080
      - MEOWMED_POLICY_SERVER=http://policy.eda:8080
    ports:
      - "80:8000"
    depends_on:
      - policy.eda
      - customer.eda
  customer.eda:
    image: meowmed-customer.eda
    profiles:
      - eda
    environment:
      - server.port=8080
      - spring.rabbitmq.host=rabbitmq
      - spring.datasource.username=root
      - spring.datasource.password=test
      - spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
      - spring.datasource.url=jdbc:mariadb://customerdb.eda:3306/Customer
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
    depends_on:
      customerdb.eda:
        condition: service_healthy
      rabbitmq:
        condition: service_started
  policy.eda:
    image: meowmed-policy.eda
    profiles:
      - eda
    environment:
      - server.port=8080
      - RABBIT_HOST=rabbitmq
      - spring.rabbitmq.host=rabbitmq
      - spring.datasource.username=user
      - spring.datasource.password=123456789
      - spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
      - spring.datasource.url=jdbc:mariadb://policydb.eda:3306/Policy
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
    depends_on:
      policydb.eda:
        condition: service_healthy
      rabbitmq:
        condition: service_started
  notification.eda:
    image: meowmed-notification.eda
    profiles:
      - eda
    environment:
      - spring.rabbitmq.host=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_started
  customerdb.eda:
    image: mariadb:latest
    profiles:
      - eda
    environment:
      <<: *dbcredentials
      MYSQL_DATABASE: Customer
    healthcheck:
      <<: *dbhealthcheck
    volumes:
      - customerdb_data_eda:/var/lib/mysql
  policydb.eda:
    image: mariadb:latest
    profiles:
      - eda
    environment:
      <<: *dbcredentials
      MYSQL_DATABASE: Policy
    healthcheck:
      <<: *dbhealthcheck
    volumes:
      - policydb_data_eda:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:management-alpine
    profiles:
      - eda

volumes:
  customerdb_data_eda:
  policydb_data_eda:
  customerdb_data_rda:
  policydb_data_rda:
