version: '3.7'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "81:8080"
    volumes:
      - ./Meowmed+_REST.yaml:/usr/share/nginx/html/Meowmed+_REST.yaml
    environment:
      API_URL: ./Meowmed+_REST.yaml

  ui.rda:
    build:
      args:
        mode: "prod"
        customerService: "http://customer.rda:8080"
        policyService: "http://policy.rda:8080"
      context: ./UI
      dockerfile: Dockerfile
    env_file:
      - ./UI/ui.env
  policy.rda:
    build:
      context: ./RDA/PolicyService
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
  customer.rda:
    build:
      context: ./RDA/CustomerService
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
  notification.rda:
    build:
      context: ./RDA/NotificationService
      dockerfile: Dockerfile

  ui.eda:
    build:
      args:
        mode: "prod"
        customerService: "http://customer.eda:8081"
        policyService: "http://policy.eda:8080"
      context: ./UI
      dockerfile: Dockerfile
    env_file:
      - ./UI/ui.env
  customer.eda:
    build:
      context: ./EDA/
      dockerfile: ./CustomerService/Dockerfile
      args:
        service: CustomerService
    ports:
      - "8071:8081"
  notification.eda:
    build:
      context: ./EDA/
      dockerfile: ./NotificationService/Dockerfile
      args:
        service: NotificationService
  policy.eda:
    build:
      context: ./EDA/
      dockerfile: ./PolicyService/Dockerfile
      args:
        service: PolicyService
    ports:
      - "8072:8080"
