version: '3.7'
services:
############################################# Customer Service #########################################################
  customer:
    build:
      context: ./
      dockerfile: ./CustomerService/Dockerfile
      args:
        service: CustomerService
    container_name: customer-service
    networks:
      - "default"
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.datasource.url=jdbc:mariadb://customerdb:3306/Customer
      - spring.datasource.username=root
      - spring.datasource.password=test
      - spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
      - server.port=8080
      - spring.jpa.hibernate.ddl-auto=create-drop
  #    - spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
    ports:
      - "81:8080"
    depends_on:
      customerdb:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  customerdb:
    image: mariadb:latest
    container_name: customerdb
    command: --general-log=1
    networks:
      - "default"
    environment:
      MARIADB_ROOT_PASSWORD: test
      MYSQL_DATABASE: Customer
      MYSQL_USER: user
      MYSQL_PASSWORD: test12345
    healthcheck:
      test: "mariadb --user=root --password=$$MARIADB_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 20s
      retries: 10
    volumes:
      - customerdb_data:/var/lib/mysql


############################################# Notification Service #####################################################
  notification:
    build:
      context: ./
      dockerfile: ./NotificationService/Dockerfile
      args:
        service: NotificationService
    container_name: notification-service-l
    networks:
      - "default"
    environment:
      - spring.rabbitmq.host=rabbitmq
    depends_on:
      notificationdb:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  notificationdb:
    image: mariadb:latest
    container_name: notificationdb
    networks:
      - "default"
    environment:
      MARIADB_ROOT_PASSWORD: test
      MYSQL_DATABASE: Notification
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456789
    healthcheck:
      test: "mariadb --user=root --password=$$MARIADB_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 20s
      retries: 10
    #ports:
    #  - "3306:3306"
    volumes:
      - notificationdb_data:/var/lib/mysql


############################################### Policy Service #########################################################
  policy:
    build:
      context: ./
      dockerfile: ./PolicyService/Dockerfile
      args:
        service: PolicyService
    container_name: policy-service
    depends_on:
      policydb:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - "default"
    ports:
      - "82:8080"
    environment:
      - RABBIT_HOST=rabbitmq
      - spring.datasource.url=jdbc:mariadb://policydb:3306/Policy
      - spring.datasource.username=user
      - spring.datasource.password=123456789
      - spring.rabbitmq.host=rabbitmq
      - spring.datasource.username=root
      - spring.datasource.password=test
      - spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
      - server.port=8080
      - spring.jpa.hibernate.ddl-auto=create-drop
        #    - spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

  policydb:
    image: mariadb:latest
    container_name: policydb
    networks:
      - "default"
    environment:
      MARIADB_ROOT_PASSWORD: test
      MYSQL_DATABASE: Policy
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456789
    healthcheck:
      test: "mariadb --user=root --password=$$MARIADB_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 20s
      retries: 10
    #ports:
    #  - "3306:3306"
    volumes:
      - policydb_data:/var/lib/mysql


############################################# Billing Service ##########################################################
  billing:
    build:
      context: ./
      dockerfile: ./BillingService/Dockerfile
      args:
        service: BillingService
    container_name: billing-service
    depends_on:
      billingdb:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - "default"
    ports:
      - "83:8080"
    environment:
      - RABBIT_HOST=rabbitmq
      - spring.datasource.url=jdbc:mariadb://billingdb:3306/Billing
      - spring.datasource.username=user
      - spring.datasource.password=123456789
      - spring.rabbitmq.host=rabbitmq
      - spring.datasource.username=root
      - spring.datasource.password=test
      - spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
      - server.port=8080
      - spring.jpa.hibernate.ddl-auto=create-drop
      #    - spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

  billingdb:
    image: mariadb:latest
    container_name: billingdb
    command: --general-log=1
    networks:
      - "default"
    environment:
      MARIADB_ROOT_PASSWORD: test
      MYSQL_DATABASE: Billing
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456789
    healthcheck:
      test: "mariadb --user=root --password=$$MARIADB_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 20s
      retries: 10
    volumes:
      - billingdb_data:/var/lib/mysql


  ############################################ RabbitMQ ################################################################
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq-l
    networks:
      - "default"
    ports:
      - "15671:15671"
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"

volumes:
  policydb_data:
  notificationdb_data:
  customerdb_data:
  billingdb_data: