version: '3.7'
services:
  customer:
    build:
      context: ./CustomerService
      dockerfile: Dockerfile
    container_name: customer-service
    networks:
      - "default"
    environment:
      - RABBIT_HOST=rabbitmq
    ports:
      - "81:8081"
    depends_on:
      - customerdb
  customerdb:
    image: mariadb:latest
    container_name: customerdb
    networks:
      - "default"
    environment:
      - MARIADB_ROOT_PASSWORD=test
  notification:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    container_name: notification-service
    networks:
      - "default"
    environment:
      - RABBIT_HOST=rabbitmq
#  policy:
#    build:
#      context: ./PolicyService
#      dockerfile: Dockerfile
#    container_name: policy-service
#    networks:
#      - "default"
#    environment:
#      - RABBIT_HOST=rabbitmq
#  policydb:
#    image: mariadb:latest
#    container_name: policydb
#    networks:
#      - "default"
#    environment:
#      - MARIADB_ROOT_PASSWORD=test
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    networks:
      - "default"
    ports:
      - "15671:15671"
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"