# Für das komplette Projekt später
version: '3.7'
services:
  policy:
    build:
      context: ./PolicyService
      dockerfile: Dockerfile
    container_name: policy-service
    networks:
      - "default"
    ports:
      - 81:8080
  notification:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    container_name: notification-service
    networks:
      - "default"
    ports:
      - 82:8080
