# Für das komplette Projekt später
version: '3.7'
services:
  ui:
    build:
      context: ../UI
      dockerfile: Dockerfile
    container_name: ui-service
    networks:
      - "default"
    ports:
      - 80:80 
  policy:
    build:
      context: ./PolicyService
      dockerfile: Dockerfile
    container_name: policy-service
    networks:
      - "default"
    ports:
      - 81:8080
  #notification:
  #  build:
  #    context: ./NotificationService
  #    dockerfile: Dockerfile
  #  container_name: notification-service
  #  networks:
  #    - "default"
  #  ports:
  #    - 82:8080
  customer:
    build:
      context: ./CustomerService
      dockerfile: Dockerfile
    container_name: customer-service
    networks:
      - "default"
    ports:
      - 83:8080   
    environment:
      - docker.customerurl=customer12