# Für das komplette Projekt später
version: '3.7'
services:
  ui:
    build:
      args:
        mode: "prod"
        customerService: "http://customer:8080"
        policyService: "http://policy:8080"
      context: ../UI
      dockerfile: Dockerfile
    container_name: ui-service
    env_file:
      - ../UI/ui.env
    networks:
      - "default"
    ports:
      - 80:8000 
  policy:
    build:
      context: ./PolicyService
      dockerfile: Dockerfile
    container_name: policy-service
    networks:
      - "default"
    ports:
      - 81:8080
    depends_on: 
      - policydb
    environment:
      - spring.datasource.url=jdbc:mariadb://policydb:3306/Policy
      - spring.datasource.username=user
      - spring.datasource.password=123456789
      - docker_customerurl=customer
      - docker_notificationurl=notification
      - docker_debugmode=false
  policydb:
    image: mariadb:latest
    container_name: policydb
    networks:
      - "default"
    environment:
      MARIADB_ROOT_PASSWORD: test
      MYSQL_DATABASE: Policy
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456789
    #ports:
    #  - "3306:3306"
    volumes:
      - policydb_data:/var/lib/mysql
  customer:
    build:
      context: ./CustomerService
      dockerfile: Dockerfile
    container_name: customer-service
    depends_on: 
      - customerdb
    networks:
      - "default"
    ports:
      - 82:8080   
    environment:
      - spring.datasource.url=jdbc:mariadb://customerdb:3306/Customer
      - spring.datasource.username=user
      - spring.datasource.password=123456789
      - docker_notificationurl=notification
  customerdb:
    image: mariadb:latest
    container_name: customerdb
    networks:
      - "default"
    environment:
      MARIADB_ROOT_PASSWORD: test
      MYSQL_DATABASE: Customer
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456789
    #ports:
    #  - "3306:3306"
    volumes:
      - customerdb_data:/var/lib/mysql
  notification:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    container_name: notification-service
    networks:
      - "default"
    ports:
      - 83:8080
    environment:
      - spring_mail_host=smtp.gmail.com
      - spring_mail_port=587
      - spring_mail_username=meowmedservice@gmail.com
      - spring_mail_password=yqanpbjhupnllbcz
      - spring_mail_properties.mail.smtp.auth=true
      - spring_mail_properties.mail.smtp.starttls.enable=true

volumes:
  policydb_data:
  customerdb_data: