version: '3.7'
services:
  ui:
    build:
      context: .
      target: test
    env_file:
      - ui.env
    environment:
      - MEOWMED_CUSTOMER_SERVER=testing
      - MEOWMED_POLICY_SERVER=testing
    container_name: meowmed+
    networks:
      - "default"
    ports:
      - 80:8000
